name: jarvis
description: Life Tracker App with Advanced UI/UX and Gamification

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Dependencies
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  intl: ^0.18.1

  # UI/UX Enhancement
  flutter_staggered_animations: ^1.1.1
  percent_indicator: ^4.2.3
  fl_chart: ^0.63.0
  lottie: ^2.4.0
  shimmer: ^3.0.0
  animated_text_kit: ^4.2.2
  flutter_spinkit: ^5.2.0
  confetti: ^0.7.0
  avatar_glow: ^2.0.2

  # Animation and Splash
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  flutter_animate: ^4.1.1+1

  # Calendar and Date Picking
  table_calendar: ^3.0.9

  # Image Handling
  image_picker: ^0.8.7+5
  screenshot: ^3.0.0
  share_plus: ^7.0.2
  path_provider: ^2.0.15

  # Voice and Audio Features
  # speech_to_text: ^7.0.0  # Temporarily disabled due to build issues

  # Cupertino Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/images/meals/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700